### ISSUE TITLE
too complex merge conflict?

### ISSUE THREAD

**Issue by FelixWuYH** [FelixWuYH/BS_project_1081#16]
Does anyone know the best way to solve this kind of problems?
Ref. https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line

**Comment by ken88824** [comment]
除了讓組長做版本控管外，也要注意每個人的任務不衝突，組長在對原始版本做merge前確保更改部分盡量不影響其他部分，並且只要有新版本出現，組長除了告知其他人外，其他人也需要同步更改自己的版本。

**Comment by FelixWuYH** [comment]
Below is an example from a new branch 'yu-shan-young-master' (team 2).

Step 1) Install Git for windows from the following URL.
https://gitforwindows.org/

Step 2) Move to the repository under the folder of GitHub desktop.
![GitHub Desktop 2019_9_3 下午 02_42_35](https://user-images.githubusercontent.com/13898512/64149730-4e257680-ce59-11e9-8ffb-2e6a381527f1.png)

3) Execute Git command line instructions as suggested.
![選取 命令提示字元 2019_9_3 下午 02_55_14](https://user-images.githubusercontent.com/13898512/64150477-e6702b00-ce5a-11e9-8973-a17e846e5820.png)
